
const bookCategories = [
  'Computer',
  'Programming',
  'Design',
  'Action',
  'Adventure',
  'Art',
  'Aarchitecture',
  'Autobiography',
  'Anthology',
  'Biography',
  'Business',
  'Children',
  'Crafts',
  'Classic',
  'Cookbook',
  'Comic',
  'Diary',
  'Encyclopedia',
  'Drama',
  'Guide',
  'Fairytale',
  'Security',
  'Fitness',
  'Health',
  'Fantasy',
  'History',
  'Home',
  'Historical',
  'Garden',
  'Humor',
  'Horror',
  'Journal',
  'Mystery',
  'Math',
  'Paranormal',
  'Memoir',
  'Philosophy',
  'Poetry',
  'Prayer',
  'Political',
  'Religion',
  'Romance',
  'Fiction',
  'Review',
  'Short',
  'Science',
  'Suspense',
  'Help',
  'Thriller',
  'Sports',
  'Western',
  'Travel',
  'Young',
  'Crime'
];
const gameCategories = [
  'Characters',
  'Animations',
  'Animals',
  'Creatures',
  'Foley',
  'Transportation',
  'Weapons',
  'Environments',
  'Vehicles',
  'GUI',
  'Bundles',
  'Furniture',
  'Bundle'
];

const graphicCategories = [
  'Vectors',
  'Backgrounds',
  'Print Templates',
  'Logo Templates',
  'Web Elements',
  'Email Templates',
  'Presentation Templates',
  'Icons',
  'Fonts',
  'YouTube',
  'Facebook',
  'Instagram',
  'LinkedIn',
  'TikTok',
  'Twitter',
  'Vimeo',
  'Twitch',
  'Bundle'
];

const photoCategories = [
  'Family',
  'Fashion',
  'Food',
  'Drink',
  'Fitness',
  'Healthcare',
  'Holidays',
  'Industrial',
  'Music',
  'City',
  'Creativity',
  'Culture',
  'Education',
  'Backgrounds',
  'Animals',
  'Architecture',
  'Business',
  'Nature',
  'Vehicles',
  'Outdoors',
  'Science',
  'Sports',
  'Transportation',
  'Travel',
  'Wedding',
  'Vintage',
  'People',
  'Agriculture',
  'Home',
  'Lifestyle'
];

const videoCategories = [
  'People',
  'Nature',
  'Business',
  'Corporate',
  'Food',
  'Lifestyle',
  'Sports',
  'Building',
  'Medical',
  'Technology',
  'Industrial',
  'Holidays',
  'Vehicles',
  'City',
  'Education',
  'Overhead',
  'Time Lap',
  'Science',
  'Slow Motion',
  'Construction',
  'Special effects',
  'Kids',
  'Religious',
  'Weather',
  'Military',
  'Stop Mot',
  'Cartoons'
];

const audioCategories = [
  'Ambient',
  'Children',
  'Cinematic',
  'Classical',
  'Corporate',
  'Country, Western',
  'Drum & Bass, Breakbeat',
  'Electronica',
  'Experimental, Abstract',
  'Folk, Acoustic',
  'Funk, Groove',
  'Hip-Hop',
  'Holiday & Seasonal',
  'House',
  'Jazz',
  'Percussion',
  'Pop',
  'Rock',
  'Soul, R&B',
  'Vocals, Voice',
  'World Beat',
  'Game',
  'Urban',
  'Domestic',
  'Nature',
  'Industrial',
  'Human',
  'Transitions',
  'Futuristic',
  'Interface',
  'Animals',
  'Creatures',
  'Foley',
  'Miscellaneous',
  'Vehicles',
  'Voices'
];

module.exports = {
    bookCategories: bookCategories,
    gameCategories: gameCategories,
    graphicCategories: graphicCategories,
    photoCategories: photoCategories,
    videoCategories: videoCategories,
    audioCategories: audioCategories
};